// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB79WO-Hr-WoA-zShzhlDf3pn1nhwvYk0',
    appId: '1:179925532044:web:e43a97beb4e1892354aaa9',
    messagingSenderId: '179925532044',
    projectId: 'daurfit',
    authDomain: 'daurfit.firebaseapp.com',
    storageBucket: 'daurfit.firebasestorage.app',
    measurementId: 'G-YPMNB28W0K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKp5dMZOawNskJMJktu_53MnmccEaUzZk',
    appId: '1:179925532044:android:6756796d5a2804a454aaa9',
    messagingSenderId: '179925532044',
    projectId: 'daurfit',
    storageBucket: 'daurfit.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIWpX0sZZTV7BaYq6kJVhKuCuHXbQv08s',
    appId: '1:179925532044:ios:1593525fe0d5c61654aaa9',
    messagingSenderId: '179925532044',
    projectId: 'daurfit',
    storageBucket: 'daurfit.firebasestorage.app',
    androidClientId: '179925532044-uhdmntns5466kjvpavdlv60n5f5imr1j.apps.googleusercontent.com',
    iosClientId: '179925532044-0vbu0hp2odi7ekq9h470sakm5j81hc2i.apps.googleusercontent.com',
    iosBundleId: 'com.siraj.daur',
  );
}
