// Generated from a researched vocabulary of how Bangladeshis name food: English, romanized Bangla
// (every common spelling) and Bangla script, one concept per line. Sources: Wikipedia (Bangladeshi
// cuisine, fishes, sweets), Banglapedia (vegetables, pitha), BdFISH, Hortex export list; Oct 2026.
// A word in more than one line (kola, jam, dim, jol…) is ambiguous on purpose: search tries every
// meaning. The first word of a line is its canonical form. Edit freely: one line per food.

const foodWordGroups = <List<String>>[
  ['bhat', 'bhaat', 'vat', 'vaat', 'rice', 'boiled rice', 'steamed rice', 'plain rice', 'ভাত'],
  ['chal', 'chaal', 'chaul', 'raw rice', 'uncooked rice', 'চাল'],
  ['panta bhat', 'panta', 'panta vat', 'pantha bhat', 'fermented soaked rice', 'watered rice', 'পান্তা ভাত', 'পান্তা'],
  ['polao', 'polaw', 'polau', 'pulao', 'pulav', 'pilaf', 'pilau', 'পোলাও'],
  ['morog polao', 'murog polao', 'morag polao', 'chicken pulao', 'মোরগ পোলাও'],
  ['akhni', 'akni', 'akhni pulao', 'আখনি'], // Sylhet/Chittagong spiced meat rice
  [
    'khichuri',
    'khichuree',
    'khichri',
    'khichudi',
    'khicuri',
    'khichdi',
    'rice and lentil porridge',
    'খিচুড়ি',
    'খিচুরি',
  ],
  ['bhuna khichuri', 'vuna khichuri', 'dry khichdi', 'ভুনা খিচুড়ি'],
  [
    'letka khichuri',
    'patla khichuri',
    'naram khichuri',
    'soft khichdi',
    'runny khichdi',
    'লেটকা খিচুড়ি',
    'পাতলা খিচুড়ি',
    'নরম খিচুড়ি',
  ],
  ['biriyani', 'biryani', 'biriani', 'birani', 'বিরিয়ানি'],
  [
    'kacchi',
    'kachchi',
    'kachi',
    'kacci',
    'kacchi biriyani',
    'kacchi biryani',
    'mutton kacchi',
    'কাচ্চি',
    'কাচ্চি বিরিয়ানি',
  ], // raw-meat layered biryani, usually khasi
  ['tehari', 'tehri', 'tehary', 'তেহারি'], // usually beef, one-pot, mustard oil
  ['jorda', 'zorda', 'jarda', 'sweet saffron rice', 'জর্দা'], // also means chewing tobacco
  ['fried rice', 'egg fried rice', 'chinese fried rice', 'ফ্রাইড রাইস'],
  ['jau', 'jaou', 'jao', 'rice porridge', 'congee', 'জাউ'],
  ['ata', 'atta', 'aata', 'whole wheat flour', 'আটা'], // ata also = custard apple (আতা)
  ['moyda', 'moida', 'maida', 'refined flour', 'all purpose flour', 'ময়দা'],
  ['ruti', 'roti', 'ata ruti', 'chapati', 'flatbread', 'রুটি', 'আটার রুটি'],
  ['chaler ruti', 'chaler ata ruti', 'rice flour roti', 'চালের রুটি'],
  ['porota', 'parota', 'paratha', 'porotha', 'parotta', 'parata', 'পরোটা'],
  ['dim porota', 'dim paratha', 'egg paratha', 'ডিম পরোটা'],
  ['moglai', 'mughlai', 'moglai porota', 'mughlai paratha', 'মোগলাই', 'মোগলাই পরোটা'],
  ['luchi', 'loochi', 'fried puffed bread', 'লুচি'],
  ['puri', 'poori', 'পুরি'], // in BD often a stuffed snack puri
  ['dal puri', 'dalpuri', 'daal puri', 'lentil stuffed puri', 'ডাল পুরি', 'ডালপুরি'],
  ['alu puri', 'aloo puri', 'potato stuffed puri', 'আলু পুরি'],
  ['nan', 'naan', 'nan ruti', 'নান', 'নান রুটি'],
  ['bakorkhani', 'bakarkhani', 'bakhorkhani', 'বাকরখানি'],
  ['pauruti', 'paoruti', 'pau ruti', 'bread', 'sliced bread', 'loaf bread', 'toast', 'পাউরুটি'],
  ['bon', 'bonruti', 'bun', 'বন', 'বনরুটি'],
  ['dim pauruti', 'dim toast', 'french toast', 'egg toast', 'ডিম পাউরুটি'],
  ['muri', 'moori', 'puffed rice', 'মুড়ি'],
  ['chira', 'chida', 'chura', 'flattened rice', 'beaten rice', 'poha', 'চিড়া', 'চিঁড়া'],
  ['khoi', 'khai', 'popped rice', 'খই'],
  ['suji', 'shuji', 'sooji', 'semolina', 'rava', 'সুজি'],
  ['oats', 'oatmeal', 'ওটস'],
  ['cornflakes', 'breakfast cereal', 'কর্নফ্লেক্স'],
  ['noodles', 'nudols', 'instant noodles', 'নুডলস'],
  ['chowmin', 'chaumin', 'chowmein', 'chow mein', 'fried noodles', 'চাউমিন'],
  ['pasta', 'macaroni', 'পাস্তা', 'মেকারনি'],
  ['sagu', 'sabu', 'sabudana', 'sago', 'tapioca pearls', 'সাগু', 'সাবু', 'সাবুদানা'],
  ['bhutta', 'vutta', 'corn', 'maize', 'sweet corn', 'ভুট্টা'],
  ['job', 'barli', 'barley', 'যব', 'বার্লি'],
  ['mach', 'maach', 'mas', 'maas', 'macher', 'maser', 'mas er', 'fish', 'মাছ', 'মাছের'],
  ['rui', 'rui mach', 'ruhi', 'rohu', 'রুই'],
  ['katla', 'catla', 'কাতলা'],
  ['mrigel', 'mrigal', 'mirka', 'mrigal carp', 'মৃগেল', 'মিরকা'],
  ['kalibaus', 'kalibaush', 'black rohu', 'কালিবাউস'],
  ['silver carp', 'silver', 'সিলভার কার্প'],
  ['grass carp', 'গ্রাস কার্প'],
  ['carpio', 'karpio', 'common carp', 'কার্পিও'],
  ['ilish', 'elish', 'ilsha', 'ilisha', 'hilsha', 'hilsa', 'hilsa shad', 'ইলিশ'],
  ['jatka', 'juvenile hilsa', 'জাটকা'],
  ['pangas', 'pangash', 'pangus', 'pangasius', 'pangas catfish', 'basa', 'পাঙ্গাস', 'পাঙাশ'],
  ['telapia', 'tilapia', 'telapiya', 'তেলাপিয়া'],
  ['koi', 'koi mach', 'climbing perch', 'কই'],
  ['shing', 'sing', 'stinging catfish', 'শিং'],
  ['magur', 'walking catfish', 'মাগুর'],
  ['pabda', 'pabdha', 'butter catfish', 'পাবদা'],
  ['boal', 'boyal', 'wallago', 'helicopter catfish', 'বোয়াল'],
  ['air', 'aire', 'ayre', 'long whiskered catfish', 'আইড়', 'আইর'],
  ['tengra', 'tangra', 'gulsha', 'gulsha tengra', 'mystus catfish', 'টেংরা', 'গুলশা'],
  ['chitol', 'chital', 'clown knifefish', 'featherback', 'চিতল'],
  ['muitha', 'muittha', 'chitol fish dumplings', 'মুইঠা'],
  ['puti', 'punti', 'sorputi', 'shorputi', 'pool barb', 'olive barb', 'পুঁটি', 'সরপুঁটি'],
  ['mola', 'mola mach', 'mola carplet', 'মলা'],
  ['kachki', 'kaski', 'ganges river sprat', 'কাচকি'],
  ['chapila', 'indian river shad', 'চাপিলা'],
  ['bata', 'bata labeo', 'বাটা'],
  ['shol', 'sol', 'snakehead striped', 'শোল'],
  ['gojar', 'gozar', 'giant snakehead', 'গজার'],
  ['taki', 'spotted snakehead', 'টাকি'],
  ['baim', 'bain', 'spiny eel', 'eel', 'বাইম', 'বাইন'],
  ['bele', 'baila', 'tank goby', 'বেলে'],
  ['kakila', 'garfish', 'needlefish', 'কাকিলা'],
  ['poa', 'pama croaker', 'পোয়া'],
  ['koral', 'bhetki', 'vetki', 'barramundi', 'asian sea bass', 'কোরাল', 'ভেটকি'],
  ['rupchanda', 'rupchada', 'pomfret', 'silver pomfret', 'রূপচাঁদা', 'রুপচাঁদা'],
  ['loitta', 'lotia', 'loittya', 'bombay duck', 'লইট্টা', 'লইটা'], // fresh or dried
  ['tuna', 'টুনা'],
  ['chingri', 'chingdi', 'icha', 'isha', 'shrimp', 'prawn', 'চিংড়ি', 'ইচা'], // icha = small shrimp
  [
    'golda',
    'golda chingri',
    'giant freshwater prawn',
    'scampi',
    'গলদা',
    'গলদা চিংড়ি',
  ], // often called 'lobster' locally
  ['bagda', 'bagda chingri', 'tiger prawn', 'tiger shrimp', 'বাগদা', 'বাগদা চিংড়ি'],
  ['kakra', 'kankra', 'crab', 'কাঁকড়া'],
  ['shutki', 'sutki', 'shuntki', 'dried fish', 'শুঁটকি', 'শুটকি'],
  ['shutki bhorta', 'sutki vorta', 'dried fish mash', 'শুঁটকি ভর্তা'],
  ['macher dim', 'ilish er dim', 'fish roe', 'fish eggs', 'মাছের ডিম'],
  ['macher matha', 'mas er matha', 'fish head', 'মাছের মাথা'],
  ['muri ghonto', 'murighonto', 'fish head with rice dal', 'মুড়িঘণ্ট'],
  ['mach bhaja', 'maach bhaja', 'mas vaja', 'fried fish', 'fish fry', 'মাছ ভাজা'],
  ['macher jhol', 'macher torkari', 'mas er salon', 'fish curry', 'মাছের ঝোল', 'মাছের তরকারি'],
  ['shorshe ilish', 'sorshe ilish', 'sorisha ilish', 'hilsa in mustard sauce', 'সর্ষে ইলিশ', 'সরিষা ইলিশ'],
  ['bhapa ilish', 'vapa ilish', 'steamed hilsa', 'ভাপা ইলিশ'],
  ['ilish paturi', 'hilsa in banana leaf', 'ইলিশ পাতুরি'],
  ['chingri malaikari', 'malaikari', 'prawn malai curry', 'চিংড়ি মালাইকারি'],
  ['mangsho', 'mangso', 'mongsho', 'gosht', 'gosto', 'mangsher', 'meat', 'মাংস', 'গোশত', 'গোস্ত'],
  ['murgi', 'murgir', 'morog', 'murog', 'chicken', 'মুরগি', 'মুরগী', 'মোরগ'],
  ['deshi murgi', 'desi murgi', 'free range chicken', 'country chicken', 'দেশি মুরগি'],
  [
    'broiler',
    'broiler murgi',
    'farmer murgi',
    'broiler chicken',
    'farm chicken',
    'ব্রয়লার',
    'ব্রয়লার মুরগি',
    'ফার্মের মুরগি',
  ],
  ['sonali', 'sonali murgi', 'sonali chicken', 'সোনালি', 'সোনালি মুরগি'],
  ['layer', 'layer murgi', 'layer hen', 'লেয়ার মুরগি'],
  [
    'leg pis',
    'leg piece',
    'raan',
    'rann',
    'chicken leg',
    'thigh',
    'লেগ পিস',
    'রান',
  ], // don't map 'drumstick' to sajna here
  ['breast pis', 'breast piece', 'chicken breast', 'ব্রেস্ট পিস'],
  ['gorur mangsho', 'gorur gosht', 'gorur mangso', 'goru', 'beef', 'গরুর মাংস', 'গরুর গোশত'],
  [
    'khasi',
    'khashi',
    'khasir mangsho',
    'khashir gosht',
    'chagol',
    'pathar mangsho',
    'mutton',
    'goat meat',
    'খাসি',
    'খাসির মাংস',
    'ছাগলের মাংস',
    'পাঠার মাংস',
  ],
  ['bhera', 'vera', 'bherar mangsho', 'lamb', 'sheep meat', 'ভেড়া', 'ভেড়ার মাংস'],
  ['mohish', 'mohisher mangsho', 'buffalo', 'মহিষ', 'মহিষের মাংস'],
  ['hash', 'haash', 'hasher mangsho', 'duck', 'হাঁস', 'হাঁসের মাংস'],
  ['kobutor', 'kabutor', 'koitor', 'pigeon', 'squab', 'কবুতর'],
  ['koel', 'koyel', 'quail', 'কোয়েল'],
  ['turkey', 'tarki', 'টার্কি'],
  ['kolija', 'koliza', 'liver', 'কলিজা'],
  ['gila', 'gila kolija', 'gizzard', 'গিলা', 'গিলা কলিজা'],
  ['nolli', 'nalli', 'bone marrow', 'marrow bone', 'নলি'],
  ['paya', 'paye', 'trotters', 'paya soup', 'পায়া'],
  ['bhuri', 'vuri', 'bot', 'tripe', 'ভুঁড়ি', 'বট'],
  ['mogoj', 'mogz', 'brain', 'মগজ'],
  ['kima', 'keema', 'minced meat', 'কিমা'],
  ['kofta', 'kopta', 'meatballs', 'কোফতা', 'কোপ্তা'],
  ['sausage', 'সসেজ'],
  ['nugget', 'nuggets', 'chicken nuggets', 'নাগেট'],
  ['dim', 'deem', 'dimer', 'deemer', 'anda', 'egg', 'ডিম', 'ডিমের'], // dim also = fish roe in 'macher dim'
  ['hali', 'ek hali', 'four eggs', 'set of four', 'হালি'], // eggs/bananas sold per hali (4)
  [
    'sheddho dim',
    'siddho dim',
    'shiddho dim',
    'dim sheddho',
    'dim siddho',
    'boiled egg',
    'hard boiled egg',
    'সিদ্ধ ডিম',
    'ডিম সিদ্ধ',
  ],
  [
    'omlet',
    'mamlet',
    'dim bhaja',
    'dim vaja',
    'omelette',
    'omelet',
    'ওমলেট',
    'মামলেট',
    'ডিম ভাজা',
  ], // dim bhaja usually = omelette
  [
    'poch',
    'dim poch',
    'pouch',
    'sunny side up',
    'fried egg',
    'poached egg',
    'পোচ',
    'ডিম পোচ',
  ], // poch = sunny-side fried, not poached
  [
    'dimer torkari',
    'dim curry',
    'dimer jhol',
    'dim bhuna',
    'dimer dalna',
    'egg curry',
    'ডিমের তরকারি',
    'ডিম ভুনা',
    'ডিমের কারি',
  ],
  ['dim bhorta', 'dim vorta', 'mashed egg', 'ডিম ভর্তা'],
  ['hasher dim', 'duck egg', 'হাঁসের ডিম'],
  ['deshi dim', 'desi dim', 'deshi murgir dim', 'free range egg', 'local egg', 'দেশি ডিম'],
  ['farmer dim', 'farm dim', 'farm egg', 'ফার্মের ডিম'],
  ['koyeler dim', 'koel dim', 'quail egg', 'কোয়েলের ডিম'],
  ['dimer sada', 'dimer shada', 'egg white', 'ডিমের সাদা'],
  ['dimer kusum', 'egg yolk', 'ডিমের কুসুম'],
  ['dal', 'daal', 'dail', 'dhal', 'lentils', 'lentil soup', 'ডাল'],
  ['moshur', 'mosur', 'musur', 'masoor', 'moshur dal', 'red lentil', 'masoor dal', 'মসুর', 'মসুর ডাল'],
  ['mug', 'mung', 'moong', 'mug dal', 'muger dal', 'mung bean', 'moong dal', 'green gram', 'মুগ', 'মুগ ডাল'],
  ['mashkalai', 'mash kalai', 'maskalai', 'black gram', 'urad dal', 'মাষকলাই', 'মাসকলাই'],
  [
    'chola',
    'chhola',
    'boot',
    'but',
    'booter dal',
    'cholar dal',
    'chickpea',
    'bengal gram',
    'chana dal',
    'ছোলা',
    'বুট',
    'বুটের ডাল',
    'ছোলার ডাল',
  ],
  ['chola bhuna', 'chola buna', 'boot bhuna', 'spiced chickpeas', 'chana masala', 'ছোলা ভুনা'],
  ['khesari', 'kheshari', 'grass pea', 'khesari dal', 'খেসারি'],
  ['motor', 'matar', 'motor dal', 'dried peas', 'yellow split peas', 'matar dal', 'মটর', 'মটর ডাল'],
  ['motorshuti', 'matarshuti', 'green peas', 'মটরশুঁটি'],
  ['orhor', 'arhar', 'pigeon pea', 'toor dal', 'অড়হর'],
  ['ghugni', 'ghughni', 'yellow pea curry', 'ঘুগনি'],
  ['soyabin', 'soybean', 'soya bori', 'soya chunks', 'সয়াবিন', 'সয়াবড়ি'],
  ['bori', 'dal bori', 'sun dried lentil dumplings', 'বড়ি'],
  ['shobji', 'sobji', 'sabji', 'shak shobji', 'vegetables', 'mixed vegetables', 'সবজি', 'শাকসবজি'],
  ['alu', 'aloo', 'alur', 'potato', 'আলু', 'আলুর'],
  ['mishti alu', 'misti alu', 'sweet potato', 'মিষ্টি আলু'],
  ['lau', 'lao', 'kodu', 'bottle gourd', 'calabash', 'লাউ', 'কদু'],
  ['kumra', 'mishti kumra', 'misti kumra', 'pumpkin', 'কুমড়া', 'মিষ্টি কুমড়া'],
  ['chal kumra', 'chalkumra', 'ash gourd', 'winter melon', 'চালকুমড়া'],
  ['potol', 'patol', 'pointed gourd', 'পটল'],
  ['jhinga', 'jhinge', 'jinga', 'ridge gourd', 'ঝিঙা', 'ঝিঙ্গা'],
  ['dhundul', 'dundul', 'sponge gourd', 'ধুন্দুল'],
  ['chichinga', 'chichinge', 'snake gourd', 'চিচিঙ্গা', 'চিচিঙা'],
  ['korola', 'karela', 'bitter gourd', 'bitter melon', 'করলা'],
  ['uchhe', 'ucche', 'uche', 'small bitter gourd', 'উচ্ছে'], // small korola
  ['kakrol', 'kankrol', 'teasel gourd', 'spiny gourd', 'কাঁকরোল'],
  ['dherosh', 'dheros', 'deros', 'bhindi', 'okra', 'ladies finger', 'ঢেঁড়স', 'ঢ্যাঁড়স'],
  ['begun', 'begoon', 'eggplant', 'brinjal', 'aubergine', 'বেগুন'],
  ['shim', 'sheem', 'sim', 'flat bean', 'hyacinth bean', 'শিম'],
  ['shimer bichi', 'bichi', 'bean seeds', 'শিমের বিচি'],
  ['borboti', 'barbati', 'borbati', 'yardlong bean', 'long bean', 'বরবটি'],
  ['french bean', 'beans', 'green beans', 'french beans', 'ফরাসি শিম', 'বিন'],
  ['mula', 'mulo', 'radish', 'daikon', 'মুলা', 'মূলা'],
  ['gajor', 'gajar', 'carrot', 'গাজর'],
  ['beet', 'bit', 'beetroot', 'বিট'], // not 'bit lobon'
  ['shalgom', 'salgam', 'turnip', 'শালগম'],
  ['kochu', 'mukhi kochu', 'kochur mukhi', 'taro', 'colocasia corm', 'কচু', 'মুখী কচু', 'কচুর মুখী'],
  ['kochur loti', 'loti', 'taro stolons', 'কচুর লতি'],
  ['kochu shak', 'kochur shak', 'kochu pata', 'taro leaves', 'কচু শাক', 'কচুর শাক'],
  ['ol', 'ol kochu', 'olkochu', 'elephant foot yam', 'ওল', 'ওলকচু'],
  ['mankochu', 'man kochu', 'giant taro', 'মানকচু'],
  ['mocha', 'mochar ghonto', 'banana flower', 'banana blossom', 'মোচা'],
  ['thor', 'banana stem', 'থোড়'],
  ['kacha kola', 'kach kola', 'kachkola', 'green banana', 'plantain', 'raw banana', 'কাঁচকলা', 'কাঁচা কলা'],
  ['kacha pepe', 'green papaya', 'কাঁচা পেঁপে'],
  ['echor', 'enchor', 'young jackfruit', 'এঁচোড়'],
  ['shapla', 'shapla data', 'water lily stem', 'শাপলা'],
  ['data', 'data shak', 'dnata', 'amaranth stem', 'stalk', 'ডাঁটা', 'ডাটা', 'ডাঁটাশাক'], // not English 'data'
  ['shak', 'shaak', 'sak', 'saag', 'leafy greens', 'greens', 'শাক'],
  ['lal shak', 'lal shaak', 'lal sak', 'red amaranth', 'লাল শাক'],
  ['palong', 'palong shak', 'palak', 'spinach', 'পালং', 'পালং শাক'],
  ['pui', 'pui shak', 'puishak', 'malabar spinach', 'vine spinach', 'পুঁই', 'পুঁই শাক'],
  ['kolmi', 'kolmi shak', 'kalmi', 'water spinach', 'kangkong', 'কলমি', 'কলমি শাক'],
  ['methi', 'methi shak', 'fenugreek', 'মেথি', 'মেথি শাক'],
  ['shorisha shak', 'sorisha shak', 'mustard greens', 'সরিষা শাক'],
  ['lau shak', 'lau er shak', 'bottle gourd leaves', 'লাউ শাক'],
  ['kumra shak', 'kumra pata', 'pumpkin leaves', 'কুমড়া শাক'],
  ['pat shak', 'nalita shak', 'nalita', 'jute leaves', 'পাট শাক', 'নালিতা'],
  ['helencha', 'hinche', 'buffalo spinach', 'enhydra', 'হেলেঞ্চা', 'হিঞ্চে'],
  ['thankuni', 'thankuni pata', 'indian pennywort', 'centella', 'থানকুনি'],
  ['bathua', 'bethua', 'lamb s quarters', 'বথুয়া'],
  [
    'sajna',
    'shojne',
    'sojna',
    'shajna',
    'drumstick',
    'moringa pods',
    'সজনে',
    'সজিনা',
    'সজনা',
  ], // vegetable, not chicken leg
  ['sajna pata', 'sojne pata', 'moringa leaves', 'সজনে পাতা'],
  ['fulkopi', 'phulkopi', 'fulcopi', 'cauliflower', 'ফুলকপি'],
  ['badhakopi', 'bandhakopi', 'cabbage', 'বাঁধাকপি'],
  ['olkopi', 'kohlrabi', 'ওলকপি'],
  ['broccoli', 'brokoli', 'ব্রকলি'],
  ['capsicum', 'kapsikam', 'bell pepper', 'ক্যাপসিকাম'],
  ['tomato', 'tometo', 'টমেটো'],
  ['peyaj', 'piyaj', 'peyaz', 'piaz', 'pyaj', 'onion', 'পেঁয়াজ', 'পিঁয়াজ'],
  ['peyajkoli', 'piyaj koli', 'peyaj pata', 'spring onion', 'onion greens', 'পেঁয়াজকলি', 'পেঁয়াজ পাতা'],
  ['roshun', 'rosun', 'roshon', 'garlic', 'রসুন'],
  ['ada', 'aada', 'ginger', 'আদা'],
  ['morich', 'marich', 'chili', 'chilli', 'pepper', 'মরিচ'],
  ['kacha morich', 'kancha morich', 'kacha marich', 'green chili', 'কাঁচা মরিচ'],
  [
    'shukna morich',
    'sukna morich',
    'morich gura',
    'lal morich',
    'dried red chili',
    'chili powder',
    'শুকনা মরিচ',
    'মরিচ গুঁড়া',
  ],
  ['dhonepata', 'dhonia pata', 'dhoniya pata', 'coriander leaves', 'cilantro', 'ধনেপাতা', 'ধনিয়া পাতা'],
  ['pudina', 'pudina pata', 'mint', 'পুদিনা'],
  ['shosha', 'sosa', 'khira', 'cucumber', 'শসা', 'খিরা'],
  ['lebu', 'kagoji lebu', 'jara lebu', 'lemon', 'lime', 'লেবু', 'কাগজি লেবু', 'জারা লেবু'],
  ['mushroom', 'mashrum', 'মাশরুম'],
  ['letus', 'lettuce pata', 'lettuce', 'লেটুস', 'লেটুস পাতা'],
  ['salad', 'shalad', 'সালাদ'],
  ['chui jhal', 'choi jhal', 'piper chaba stem', 'চুইঝাল'], // Khulna meat spice
  ['shatkora', 'satkora', 'shatkora citrus', 'সাতকরা'], // Sylhet
  ['bhuna', 'vuna', 'bhoona', 'dry fried curry', 'ভুনা'],
  ['jhol', 'jol', 'thin curry', 'gravy', 'ঝোল'], // jol also = water
  ['bhaja', 'vaja', 'fried', 'fry', 'ভাজা'],
  [
    'bhaji',
    'vaji',
    'alu bhaji',
    'shak bhaji',
    'stir fried vegetables',
    'sauteed vegetables',
    'ভাজি',
  ], // BD bhaji = stir-fry, not Indian fritter
  ['bhorta', 'vorta', 'bharta', 'bhurta', 'mash', 'mashed spiced dish', 'ভর্তা'],
  ['alu bhorta', 'aloo bharta', 'alu vorta', 'mashed potato spiced', 'আলু ভর্তা'],
  ['begun bhorta', 'begun vorta', 'baingan bharta', 'eggplant mash', 'বেগুন ভর্তা'],
  ['dopiaja', 'do piyaza', 'dopeyaja', 'dopiaza', 'দোপেঁয়াজা', 'দোপিয়াজা'],
  ['rezala', 'rejala', 'রেজালা'],
  ['korma', 'qorma', 'কোরমা'],
  ['kalia', 'kaliya', 'কালিয়া'],
  ['torkari', 'tarkari', 'curry', 'side dish', 'vegetable curry', 'তরকারি'],
  [
    'curry',
    'kari',
    'salon',
    'salun',
    'salan',
    'chalon',
    'কারি',
    'সালুন',
    'ছালুন',
  ], // salon/salun: Chittagong, Sylhet, Noakhali
  ['chorchori', 'charchari', 'mixed vegetable stir fry', 'চচ্চড়ি'],
  ['ghonto', 'ghanta', 'mixed mash curry', 'ঘণ্ট'],
  ['labra', 'labda', 'mixed vegetable medley', 'লাবড়া'],
  ['shukto', 'sukto', 'bitter vegetable stew', 'শুক্তো', 'শুক্ত'],
  ['dalna', 'light curry', 'ডালনা'],
  ['paturi', 'steamed in leaf', 'পাতুরি'],
  ['bhapa', 'vapa', 'steamed', 'ভাপা'],
  ['kosha', 'kasha', 'kosha mangsho', 'slow cooked dry curry', 'কষা', 'কষা মাংস'],
  ['kala bhuna', 'kalo bhuna', 'kalavuna', 'kala vuna', 'black beef curry', 'কালা ভুনা', 'কালো ভুনা'], // Chittagong
  ['mezbani', 'mejbani', 'mezban', 'mezbani beef', 'মেজবানি'], // Chittagong
  ['dum', 'dom', 'dum cooked', 'দম'],
  ['jhal', 'jhaal', 'zhal', 'spicy', 'hot', 'ঝাল'],
  ['jhal fry', 'jhalfry', 'jhal frezi', 'jalfrezi', 'chili fry', 'ঝাল ফ্রাই'],
  ['tok', 'amer tok', 'sour dish', 'sour', 'টক', 'আমের টক'],
  ['moshla', 'mashla', 'masala', 'spice mix', 'মসলা', 'মশলা'],
  ['achar', 'aachar', 'pickle', 'আচার'],
  ['chatni', 'chutni', 'chutney', 'চাটনি'],
  ['soup', 'shup', 'thai soup', 'স্যুপ'],
  ['kabab', 'kebab', 'kabob', 'কাবাব'],
  ['shik kabab', 'sheek kabab', 'seekh', 'seekh kebab', 'শিক কাবাব'],
  ['shami kabab', 'shami kebab', 'শামি কাবাব'],
  ['boti kabab', 'boti kebab', 'বটি কাবাব'],
  ['jali kabab', 'jali kebab', 'জালি কাবাব'],
  ['tikka', 'টিক্কা'],
  ['chap', 'chaap', 'grilled meat slab', 'চাপ'], // chap = meat; chop = croquette
  ['grill', 'grill chicken', 'grilled chicken', 'গ্রিল', 'গ্রিল চিকেন'],
  ['tanduri', 'tandoori', 'tandoori chicken', 'তন্দুরি'],
  ['roast', 'rost', 'murgir roast', 'chicken roast', 'রোস্ট'], // BD roast = rich gravy dish
  ['chicken fry', 'fry chicken', 'fried chicken', 'ফ্রাইড চিকেন', 'চিকেন ফ্রাই'],
  ['halim', 'haleem', 'হালিম'],
  ['nehari', 'nihari', 'nahari', 'নেহারি'],
  ['jhalmuri', 'jhal muri', 'jalmuri', 'spiced puffed rice', 'ঝালমুড়ি'],
  ['fuchka', 'phuchka', 'puchka', 'fuska', 'pani puri', 'golgappa', 'ফুচকা'],
  ['chotpoti', 'chatpati', 'spiced pea salad', 'চটপটি'],
  ['velpuri', 'bhelpuri', 'bhel puri', 'ভেলপুরি'],
  ['singara', 'shingara', 'singhara', 'bengali samosa', 'সিঙ্গারা', 'সিঙাড়া'],
  ['somucha', 'samucha', 'shomucha', 'samosa', 'সমুচা', 'সামুচা'],
  ['piyaju', 'peyaju', 'piaju', 'lentil fritters', 'onion fritters', 'পিয়াজু', 'পেঁয়াজু', 'পিঁয়াজু'],
  ['beguni', 'eggplant fritters', 'বেগুনি'],
  ['alur chop', 'alu chop', 'aloo chop', 'potato croquette', 'potato chop', 'আলুর চপ'],
  ['chop', 'vegetable chop', 'fish chop', 'croquette', 'চপ'],
  ['cutlet', 'katlet', 'কাটলেট'],
  ['pakora', 'pakoda', 'bora', 'fritter', 'পাকোড়া', 'বড়া'],
  ['chanachur', 'bombay mix', 'savory snack mix', 'চানাচুর'],
  ['chips', 'crisps', 'চিপস'],
  ['french fry', 'fries', 'french fries', 'ফ্রেঞ্চ ফ্রাই'],
  ['burger', 'বার্গার'],
  ['pizza', 'পিৎজা', 'পিজা'],
  ['shawarma', 'shorma', 'sharma', 'শর্মা'],
  ['sandwich', 'sendwich', 'স্যান্ডউইচ'],
  ['momo', 'dumpling', 'মোমো'],
  ['biscuit', 'biskut', 'cookies', 'crackers', 'বিস্কুট'],
  ['toast biscuit', 'toast', 'rusk', 'টোস্ট বিস্কুট'],
  ['cake', 'কেক'],
  ['nimki', 'savory fried crackers', 'নিমকি'],
  ['badam', 'china badam', 'chinabadam', 'peanuts', 'nuts', 'বাদাম', 'চিনাবাদাম'],
  ['kaju', 'kaju badam', 'cashew', 'কাজু', 'কাজু বাদাম'],
  ['kathbadam', 'almond', 'কাঠবাদাম'],
  ['kismis', 'kishmish', 'raisins', 'কিশমিশ'],
  ['pitha', 'pithe', 'pita', 'rice cake', 'পিঠা', 'পিঠে'],
  ['bhapa pitha', 'vapa pitha', 'steamed rice cake', 'ভাপা পিঠা'],
  ['chitoi', 'chitai', 'chitoi pitha', 'চিতই', 'চিতই পিঠা'],
  ['dudh chitoi', 'chitoi in sweet milk', 'দুধ চিতই'],
  ['patishapta', 'patisapta', 'stuffed crepe', 'পাটিসাপটা'],
  ['puli', 'puli pitha', 'dudh puli', 'dumpling pitha', 'পুলি', 'পুলি পিঠা', 'দুধ পুলি'],
  ['pakon', 'pakan', 'pakan pitha', 'পাকন'],
  ['tel pitha', 'teler pitha', 'fried jaggery rice cake', 'তেলের পিঠা', 'তেল পিঠা'],
  ['nakshi pitha', 'nokshi pitha', 'নকশি পিঠা'],
  ['chushi', 'chushi pitha', 'chui pitha', 'hand rolled rice noodles in milk', 'চুসি পিঠা', 'চুই পিঠা'],
  ['malpoa', 'malpua', 'মালপোয়া'],
  ['mishti', 'misti', 'sweets', 'sweetmeat', 'dessert', 'মিষ্টি'], // also adjective 'sweet'
  ['roshogolla', 'rosogolla', 'rasgulla', 'rossogolla', 'রসগোল্লা'],
  ['chomchom', 'chamcham', 'cham cham', 'চমচম'],
  ['kalojam', 'kalo jam', 'kala jam', 'kala jamun', 'কালোজাম'], // sweet; fruit is jam
  ['golap jam', 'gulab jam', 'gulab jamun', 'গোলাপজাম'], // also rose-apple fruit
  ['roshmalai', 'rosmalai', 'rasmalai', 'রসমালাই'],
  ['sondesh', 'shondesh', 'sandesh', 'সন্দেশ'],
  ['mishti doi', 'misti doi', 'sweet yogurt', 'মিষ্টি দই'],
  ['jilapi', 'jilipi', 'jalebi', 'জিলাপি'],
  ['amriti', 'omriti', 'imarti', 'অমৃতি'],
  ['firni', 'phirni', 'ground rice pudding', 'ফিরনি'],
  ['payesh', 'payes', 'paesh', 'kheer', 'khir', 'rice pudding', 'পায়েস', 'ক্ষীর'], // kheer can also mean milk solids
  ['shemai', 'semai', 'lachcha shemai', 'vermicelli pudding', 'sewai', 'সেমাই', 'লাচ্ছা সেমাই'],
  ['halua', 'halwa', 'suji halua', 'gajor halua', 'হালুয়া'],
  ['laddu', 'naru', 'nadu', 'laddoo', 'লাড্ডু', 'নাড়ু'], // naru = coconut/sesame balls
  ['balushai', 'balushahi', 'বালুশাই'],
  ['borfi', 'barfi', 'বরফি'],
  ['moa', 'muri moa', 'khoi moa', 'puffed rice balls', 'মোয়া'],
  ['batasa', 'batasha', 'sugar drops', 'বাতাসা'],
  ['pudding', 'puding', 'caramel custard', 'পুডিং'],
  ['faluda', 'falooda', 'ফালুদা'],
  ['icecream', 'aiskrim', 'ice cream', 'আইসক্রিম'],
  ['kulfi', 'malai kulfi', 'কুলফি'],
  ['jelly', 'jam', 'জেলি', 'জ্যাম'], // jam also = black plum
  ['cha', 'chaa', 'chai', 'tea', 'চা'],
  ['dudh cha', 'dudh chaa', 'milk tea', 'দুধ চা'],
  ['rong cha', 'lal cha', 'raw cha', 'liquor cha', 'black tea', 'red tea', 'plain tea', 'রং চা', 'লাল চা', 'লিকার চা'],
  ['lebu cha', 'lemon tea', 'লেবু চা'],
  ['ada cha', 'adar cha', 'ginger tea', 'আদা চা'],
  ['green tea', 'গ্রিন টি'],
  ['kofi', 'coffee', 'কফি'],
  ['cold coffee', 'কোল্ড কফি'],
  ['lassi', 'lacchi', 'lachchi', 'লাচ্ছি', 'লাস্সি'],
  ['borhani', 'burhani', 'spiced yogurt drink', 'বোরহানি'],
  ['matha', 'mattha', 'ghol', 'buttermilk', 'মাঠা', 'ঘোল'],
  ['akher ros', 'akher rosh', 'akh', 'sugarcane juice', 'আখের রস', 'আখ'],
  ['khejur ros', 'khejurer rosh', 'date palm sap', 'খেজুরের রস'],
  ['daber pani', 'dab', 'daab', 'coconut water', 'green coconut', 'ডাবের পানি', 'ডাব'],
  ['shorbot', 'sharbat', 'sorbot', 'lebur shorbot', 'sweet drink', 'lemonade', 'শরবত', 'লেবুর শরবত'],
  ['mint lemon', 'lemon mint', 'mint lemonade', 'মিন্ট লেমন'],
  ['jus', 'juice', 'জুস'],
  ['pani', 'jol', 'water', 'পানি', 'জল'],
  [
    'coke',
    'pepsi',
    'sprite',
    '7up',
    'mojo',
    'rc cola',
    'cold drinks',
    'soft drink',
    'soda',
    'cola',
    'কোক',
    'পেপসি',
    'স্প্রাইট',
    'সেভেন আপ',
    'মোজো',
    'কোল্ড ড্রিংকস',
  ], // Mojo, RC = local brands
  ['speed', 'tiger', 'energy drink', 'স্পিড', 'টাইগার'],
  ['milkshake', 'shake', 'মিল্কশেক'],
  ['horlicks', 'malted milk drink', 'হরলিক্স'],
  ['isobgul', 'isabgul', 'psyllium husk drink', 'ইসবগুল'],
  ['fol', 'phol', 'fal', 'fruit', 'ফল', 'ফলমূল'],
  ['paka', 'ripe', 'পাকা'],
  ['kacha', 'kancha', 'raw', 'unripe', 'green', 'কাঁচা'],
  ['aam', 'am', 'amer', 'mango', 'আম'],
  ['kacha aam', 'kacha am', 'green mango', 'raw mango', 'কাঁচা আম'],
  ['kathal', 'kanthal', 'jackfruit', 'কাঁঠাল'],
  ['lichu', 'lichi', 'bombai lichu', 'lychee', 'লিচু'],
  [
    'kola',
    'kela',
    'shagor kola',
    'sabri kola',
    'champa kola',
    'banana',
    'কলা',
    'সাগর কলা',
    'সবরি কলা',
    'চাঁপা কলা',
  ], // kola also = cola
  ['peyara', 'piyara', 'goyam', 'guava', 'পেয়ারা', 'গোয়াম'],
  ['pepe', 'pape', 'papaya', 'পেঁপে'],
  ['anaros', 'anarosh', 'anaras', 'pineapple', 'আনারস'],
  ['jam', 'kalo jam', 'black plum', 'java plum', 'jamun', 'জাম'], // not jam/jelly or kalojam sweet
  ['jamrul', 'golap jam', 'rose apple', 'wax apple', 'water apple', 'জামরুল', 'গোলাপজাম'],
  ['jambura', 'batabi lebu', 'pomelo', 'জাম্বুরা', 'বাতাবি লেবু'],
  ['bel', 'beler shorbot', 'bael', 'stone apple', 'বেল', 'বেলের শরবত'],
  ['kodbel', 'kothbel', 'kotbel', 'elephant apple', 'wood apple', 'কদবেল', 'কৎবেল'],
  ['amra', 'hog plum', 'ambarella', 'আমড়া'],
  ['kamranga', 'star fruit', 'carambola', 'কামরাঙা', 'কামরাঙ্গা'],
  ['boroi', 'borai', 'kul', 'jujube', 'indian plum', 'বরই', 'কুল'],
  ['tormuj', 'tarmuj', 'tarbuj', 'watermelon', 'তরমুজ'],
  ['bangi', 'futi', 'muskmelon', 'cantaloupe', 'বাঙ্গি', 'ফুটি'],
  [
    'dalim',
    'bedana',
    'beddana',
    'pomegranate',
    'ডালিম',
    'বেদানা',
  ], // bedana = sweet imported pomegranate; also a lychee variety
  ['angur', 'angoor', 'grapes', 'আঙুর', 'আঙ্গুর'],
  ['khejur', 'khajur', 'dates', 'খেজুর'],
  ['narkel', 'narikel', 'narkol', 'coconut', 'নারকেল', 'নারিকেল'],
  ['tal', 'taal', 'taler shash', 'tal shash', 'palmyra palm fruit', 'ice apple', 'তাল', 'তালের শাঁস'],
  ['apel', 'apple', 'আপেল'],
  ['komola', 'kamala', 'orange', 'mandarin', 'কমলা'],
  ['malta', 'green orange', 'মাল্টা'],
  ['nashpati', 'naspati', 'pear', 'নাশপাতি'],
  ['jolpai', 'jalpai', 'indian olive', 'জলপাই'],
  ['sofeda', 'sabeda', 'sapodilla', 'chikoo', 'সফেদা'],
  ['ata', 'sharifa', 'custard apple', 'sugar apple', 'আতা', 'শরিফা'], // ata also = wheat flour (আটা)
  ['lotkon', 'latkan', 'burmese grape', 'লটকন'],
  ['dragon', 'dragon fruit', 'ড্রাগন ফল'],
  ['tetul', 'tentul', 'tamarind', 'তেঁতুল'],
  ['amloki', 'amla', 'indian gooseberry', 'আমলকী', 'আমলকি'],
  ['dudh', 'doodh', 'dudher', 'milk', 'দুধ'],
  [
    'guro dudh',
    'gura dudh',
    'dano',
    'marks',
    'milk powder',
    'powdered milk',
    'গুঁড়া দুধ',
    'গুঁড়ো দুধ',
  ], // Dano/Marks = brands
  ['condensed milk', 'কনডেন্সড মিল্ক'],
  ['doi', 'dohi', 'tok doi', 'yogurt', 'curd', 'dahi', 'দই', 'টক দই'], // tok doi = plain sour yogurt
  ['ghee', 'ghi', 'clarified butter', 'ঘি'],
  ['makhon', 'makhan', 'butter', 'মাখন'],
  ['ponir', 'panir', 'paneer', 'cheese', 'cottage cheese', 'পনির'],
  ['chhana', 'chana', 'sana', 'chhena', 'fresh curd cheese', 'ছানা'], // chana collides with chickpea
  ['khoa', 'mawa', 'milk solids', 'খোয়া', 'মাওয়া'],
  ['malai', 'shor', 'sor', 'cream', 'milk skin', 'মালাই', 'সর'],
  ['tel', 'oil', 'cooking oil', 'তেল'],
  ['shorisher tel', 'sorishar tel', 'shorsher tel', 'mustard oil', 'সরিষার তেল', 'সর্ষের তেল'],
  ['soyabin tel', 'soybean tel', 'soybean oil', 'সয়াবিন তেল'],
  ['pam tel', 'palm tel', 'palm oil', 'পাম তেল'],
  ['jolpai tel', 'olive oil', 'জলপাই তেল', 'অলিভ অয়েল'],
  ['rice bran', 'rice bran tel', 'rice bran oil', 'রাইস ব্রান তেল'],
  ['dalda', 'vanaspati', 'vegetable ghee', 'ডালডা'],
  ['sauce', 'shosh', 'tomato sauce', 'ketchup', 'সস', 'টমেটো সস'],
  ['mayo', 'meyonij', 'mayonnaise', 'মেয়োনিজ'],
  ['shorshe', 'sorshe', 'sorisha', 'shorisha', 'sorisa', 'mustard', 'mustard seeds', 'mustard paste', 'সর্ষে', 'সরিষা'],
  ['kasundi', 'kashundi', 'mustard relish', 'কাসুন্দি'],
  ['holud', 'halud', 'turmeric', 'হলুদ'],
  ['jira', 'jeera', 'zira', 'cumin', 'জিরা'],
  ['kalojira', 'kalo jira', 'nigella', 'black cumin', 'কালোজিরা'],
  ['elach', 'elachi', 'elaichi', 'cardamom', 'এলাচ'],
  ['darchini', 'dalchini', 'cinnamon', 'দারুচিনি'],
  ['lobongo', 'labanga', 'long', 'clove', 'লবঙ্গ', 'লং'],
  ['tejpata', 'tej pata', 'bay leaf', 'তেজপাতা'],
  ['dhonia', 'dhone', 'dhonia gura', 'coriander seed', 'coriander powder', 'ধনিয়া', 'ধনে', 'ধনিয়া গুঁড়া'],
  ['golmorich', 'gol morich', 'black pepper', 'গোলমরিচ'],
  ['panch phoron', 'pach foron', 'panchforon', 'five spice mix', 'পাঁচফোড়ন'],
  ['gorom moshla', 'garam masala', 'গরম মসলা'],
  ['gur', 'khejur gur', 'akher gur', 'nolen gur', 'patali', 'jaggery', 'molasses', 'গুড়', 'খেজুরের গুড়', 'পাটালি'],
  ['chini', 'cini', 'sugar', 'চিনি'],
  ['lobon', 'labon', 'nun', 'noon', 'salt', 'লবণ', 'নুন'],
  ['bit lobon', 'bitlobon', 'kala lobon', 'black salt', 'বিট লবণ'],
  ['tasting salt', 'testing salt', 'ajinomoto', 'msg', 'টেস্টিং সল্ট'],
  ['modhu', 'madhu', 'honey', 'মধু'],
  ['til', 'sesame', 'তিল'],
  ['jafran', 'zafran', 'saffron', 'জাফরান'],
  ['golap jol', 'keora', 'kewra', 'rose water', 'kewra water', 'গোলাপজল', 'কেওড়া'],
  ['sirka', 'shirka', 'vinegar', 'সিরকা'],
  ['khabar', 'khana', 'khawa', 'khaoa', 'food', 'meal', 'খাবার', 'খাওয়া'],
  [
    'nasta',
    'nashta',
    'nastha',
    'shokaler nasta',
    'breakfast',
    'snack',
    'নাস্তা',
    'সকালের নাস্তা',
  ], // nasta = breakfast or any snack
  ['bikaler nasta', 'bikeler nasta', 'tiffin', 'afternoon snack', 'বিকালের নাস্তা', 'বিকেলের নাস্তা', 'টিফিন'],
  ['dupurer khabar', 'dupurer khana', 'lunch', 'দুপুরের খাবার'],
  ['rater khabar', 'raater khabar', 'dinner', 'supper', 'রাতের খাবার'],
  ['iftar', 'iftari', 'ইফতার', 'ইফতারি'],
  ['sehri', 'sehari', 'sahri', 'suhoor', 'সেহরি'],
  ['bati', 'baati', 'bowl', 'বাটি'],
  ['plate', 'thala', 'thal', 'প্লেট', 'থালা'],
  ['pis', 'piece', 'tukra', 'tukro', 'পিস', 'টুকরা'],
  ['slice', 'স্লাইস'],
  ['cup', 'kap', 'কাপ'],
  ['glass', 'glas', 'গ্লাস'],
  ['chamoch', 'chamuch', 'chamach', 'spoon', 'tablespoon', 'teaspoon', 'চামচ'],
  ['mutho', 'muth', 'handful', 'মুঠো', 'মুঠ'],
  ['adha', 'aadha', 'half', 'ordhek', 'half plate', 'আধা', 'হাফ', 'অর্ধেক'],
  ['full', 'ful', 'pura', 'puro', 'full plate', 'ফুল', 'পুরো'], // ful also = flower
  ['kg', 'keji', 'kilo', 'kilogram', 'কেজি'],
  ['gram', 'গ্রাম'],
  ['packet', 'প্যাকেট'],
];
